Update update-master-data.yaml

diff --git a/.github/workflows/update-master-data.yaml b/.github/workflows/update-master-data.yaml
--- a/.github/workflows/update-master-data.yaml
+++ b/.github/workflows/update-master-data.yaml
@@ -27,13 +27,23 @@ jobs:
 
       - name: Manage GameMaster
         run: |
+          # Check if both files exist
+          if [ ! -f file1.txt ] || [ ! -f file2.txt ]; then
+            echo "Error: One or both files do not exist."
+            exit 1
+          fi
+
           cmp -s file1.txt file2.txt
           if [ $? -eq 0 ]; then
             echo "Gamemaster has no changes, nothing to update."
           else
             echo "UPDATE_GAMEMASTER=true" >> $GITHUB_ENV
           fi
-          rm frontend/public/assets/GAME_MASTER.json
+      
+          if [ -f frontend/public/assets/GAME_MASTER.json ]; then
+            rm frontend/public/assets/GAME_MASTER.json
+          fi
+      
           mv master-latest.json frontend/public/assets/GAME_MASTER.json
 
       - name: Repo update
